let path = $HOME . '/.vim/'
set nocompatible
filetype off
syntax on
filetype plugin indent on
let mapleader = " "

set termguicolors
set modelines=0
set visualbell
set encoding=utf-8
set wrap
set spell
set textwidth=100
set formatoptions=tcqrn1
set tabstop=2
set smarttab
set shiftwidth=2
set softtabstop=2
set backspace=indent,eol,start
set hidden
set ttyfast
set laststatus=2
set showmode
set showcmd
set hlsearch
set incsearch
set ignorecase
set smartcase
set showmatch
set listchars=tab:.\ ,eol:¬
set background=dark
set t_Co=256
set pumheight=20
set undolevels=20
set grepprg=rg\ --vimgrep\ --smart-case\ --hidden\ --no-heading
set grepformat=%f:%l:%c:%m
set completeopt=menu,menuone,noselect
set noswapfile
set splitbelow
set splitright
set iskeyword-==
set iskeyword+=+
set fillchars+=vert:\▏

colorscheme amber

nnoremap / /\v
nnoremap Y yy
nnoremap L $
nnoremap H ^
nnoremap <silent> <Leader>s <cmd>w<CR>
vnoremap / /\v
map <leader>l :set list!<CR>
