return {
  lsp = {
    error = ' ',
    warn = ' ',
    info = ' ',
    hint = '󰌶 ',
    kind_icons = {
      Class = '  ',
      Color = '  ',
      Constant = '  ',
      Constructor = '  ',
      Enum = '  ',
      EnumMember = '  ',
      Event = '  ',
      Field = '  ',
      File = '  ',
      Folder = '  ',
      Function = '  ',
      Interface = '  ',
      Keyword = '  ',
      Method = '  ',
      Module = '  ',
      Operator = '  ',
      Property = '  ',
      Reference = '  ',
      Snippet = '  ',
      Struct = '  ',
      Text = '  ',
      TypeParameter = '  ',
      Unit = '  ',
      Value = '  ',
      Variable = '  ',
    },
  },
}
