[[mgr.prepend_keymap]]
on   = "!"
for  = "unix"
run  = 'shell "$SHELL" --block'
desc = "Open $SHELL here"

[[mgr.prepend_keymap]]
on = [ "g", "r" ]
run = 'shell -- yazi emit cd "$(git rev-parse --show-toplevel)"'
desc = "Go to git repo root"
