# Based off https://github.com/ficcdaf/ashen/blob/main/ashen.yazi/README.md
[mgr]
cwd = { fg = "#D87C4A", bold = true }
syntect_theme = "~/.config/yazi/ththeme.xml"

# Hovered
hovered = { reversed = true }
preview_hovered = { reversed = true }

# Find
find_keyword = { fg = "#4A8B8B", bold = true, italic = true, underline = true }
find_position = { fg = "#4A8B8B", bg = "reset", bold = true, italic = true }

# Marker
marker_copied = { fg = "#629C7D", bg = "#629C7D" }
marker_cut = { fg = "#C53030", bg = "#C53030" }
marker_marked = { fg = "#E5A72A", bg = "#E5A72A" }
marker_selected = { fg = "#C4693D", bg = "#C4693D" }

# Tab
tab_active = { reversed = true }
tab_inactive = {}
tab_width = 1

# Count
count_copied = { fg = "#121212", bg = "#629C7D" }
count_cut = { fg = "#121212", bg = "#C53030" }
count_selected = { fg = "#121212", bg = "#C4693D" }

# Border
border_symbol = "│"
border_style = { fg = "#801f1f" }

[mode]

normal_main = { fg = "#121212", bg = "#b4b4b4", bold = true }
normal_alt = { fg = "#b4b4b4", bg = "#212121" }

# Select mode
select_main = { fg = "#121212", bg = "#BD4C4C", bold = true }
select_alt = { fg = "#BD4C4C", bg = "#212121" }

# Unset mode
unset_main = { fg = "#121212", bg = "#D87C4A", bold = true }
unset_alt = { fg = "#D87C4A", bg = "#212121" }

[tabs]
active = { fg = "#CECDC3", bg = "#403E3C", bold = true } # tx, ui-3
inactive = { fg = "#878580", bg = "#282726" } # tx-2, ui
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Progress
progress_label = { fg = "#121212", bold = true }
progress_normal = { fg = "#C4693D", bg = "#323232" }
progress_error = { fg = "#C53030", bg = "#323232" }

# Permissions
perm_sep = { fg = "#949494", bold = true }
perm_type = { fg = "#B14242" }
perm_read = { fg = "#bbbbbb", bold = true }
perm_write = { fg = "#C4693D", bold = true }
perm_exec = { fg = "#B14242", bold = true }

[pick]
border = { fg = "#C4693D" }
active = { fg = "#DF6464", bold = true }
inactive = {}

[input]
border = { fg = "#B14242" }
title = {}
value = {}
selected = { reversed = true }

[completion]
border = { fg = "#B14242" }

[tasks]
border = { fg = "#C4693D" }
title = {}
hovered = { fg = "#bbbbbb", reversed = true }

[which]
mask = { bg = "#212121" }
cand = { fg = "#E49A44" }
rest = { fg = "#b4b4b4" }
desc = { fg = "#DF6464" }
separator = " - "
separator_style = { fg = "#B14242" }

[help]
on = { fg = "#D87C4A" }
run = { fg = "#DF6464" }
desc = { fg = "#bbbbbb" }
hovered = { reversed = true, bold = true }
footer = { fg = "#e5e5e5", bg = "#121212" }

[notify]
title_info = { fg = "#bbbbbb" }
title_warn = { fg = "#E5A72A" }
title_error = { fg = "#C53030" }

[confirm]
border = { fg = "#E5A72A" }

[filetype]
rules = [
  # Images
  { mime = "image/*", fg = "#E49A44" },

  # Media
  { mime = "{audio,video}/*", fg = "#D87C4A" },

  # Archives
  { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#DF6464" },

  # Documents
  { mime = "application/{pdf,doc,rtf}", fg = "#C4693D" },

  # Fallback
  { name = "*", fg = "#bbbbbb" },
  { name = "*/", fg = "#B14242" },
]
