local colors = {
  background = '#1c1c1c',
  light_orange = '#ffa066',
  orange = '#ff8700',
  dark_orange = '#ff5d62',
  foreground = '#c1c1c1',
  visual = '#3a3a3a',
  dark_grey = '#303030',
  grey = '#767676',
  light_grey = '#767676',
  green = '#87af87',
  dark_pink = '#af5f87',
  red = '#d75f5f',
  purple = '#af87d7',
  yellow = '#d7af5f',
}

local theme = {
  Normal                     = { bg = colors.background, fg = colors.foreground },
  NonText                    = { bg = colors.background, fg = colors.dark_grey },
  Comment                    = { bg = colors.background, fg = colors.grey },
  Conceal                    = { bg = colors.background, fg = colors.grey },
  Constant                   = { bg = colors.background, fg = colors.purple },
  Identifier                 = { bg = colors.background, fg = colors.foreground },
  Statement                  = { bg = colors.background, fg = colors.light_grey },
  Operator                   = { bg = colors.background, fg = colors.foreground },
  PreProc                    = { bg = colors.background, fg = colors.light_grey },
  Type                       = { bg = colors.background, fg = colors.grey },
  Special                    = { bg = 'none', fg = colors.light_grey },
  Error                      = { bg = 'none', fg = colors.dark_pink },
  Warning                    = { bg = 'none', fg = colors.yellow },
  ModeMsg                    = { bg = 'none', fg = colors.light_grey },
  Todo                       = { bg = 'none', fg = colors.red },
  Underlined                 = { bg = 'none', fg = colors.foreground },
  StatusLineNC               = { bg = colors.background, fg = colors.light_grey },
  WildMenu                   = { bg = '#303030', fg = colors.red },
  VertSplit                  = { bg = '#303030', fg = '#303030' },
  Title                      = { bg = 'none', fg = colors.foreground },
  LineNr                     = { bg = 'none', fg = colors.grey },
  CursorLineNr               = { bg = colors.background, fg = colors.purple },
  Cursor                     = { bg = 'none', fg = colors.purple },
  CursorLine                 = { bg = 'none', fg = 'none' },
  ColorColumn                = { bg = colors.dark_grey, fg = 'none' },
  SignColumn                 = { bg = 'none', fg = colors.light_grey },
  Visual                     = { bg = '#3a3a3a', fg = 'none' },
  VisualNOS                  = { bg = colors.dark_grey, fg = 'none' },
  Pmenu                      = { bg = '#3a3a3a', fg = 'none' },
  PmenuSbar                  = { bg = '#303030', fg = 'none' },
  PmenuSel                   = { bg = '#303030', fg = colors.purple },
  PmenuThumb                 = { bg = colors.red, fg = 'none' },
  FoldColumn                 = { bg = 'none', fg = colors.grey },
  Folded                     = { bg = '#1c1c1c', fg = colors.light_grey },
  SpecialKey                 = { bg = 'none', fg = colors.light_grey },
  IncSearch                  = { bg = colors.red, fg = '#262626' },
  Search                     = { bg = colors.purple, fg = '#262626' },
  Directory                  = { bg = 'none', fg = colors.purple },
  MatchParen                 = { bg = 'none', fg = colors.purple, bold = true },
  SpellCap                   = { bg = 'none', fg = colors.green },
  QuickFixLine               = { bg = colors.background, fg = 'none' },
  DiffAdd                    = { bg = '#303030', fg = colors.green },
  DiffChange                 = { bg = '#303030', fg = 'none' },
  DiffDelete                 = { bg = '#303030', fg = colors.dark_pink },
  DiffText                   = { bg = '#303030', fg = colors.yellow },
  helpHyperTextJump          = { bg = colors.background, fg = colors.purple },
  -- Avoid changing the foreground color from the main theme
  FloatBorder                = { link = 'XMenuBorder' },
  ActionPreviewBorder        = { link = 'XMenuBorder' },
  ActionPreviewNormal        = { link = 'XMenu' },
  CallHierarchyBorder        = { link = 'XMenuBorder' },
  CallHierarchyNormal        = { link = 'XMenu' },
  CodeActionBorder           = { link = 'XMenuBorder' },
  CodeActionNormal           = { link = 'XMenu' },
  DefinitionBorder           = { link = 'XMenuBorder' },
  DefinitionNormal           = { link = 'XMenu' },
  FinderBorder               = { link = 'XMenuBorder' },
  FinderNormal               = { link = 'XMenu' },
  HoverBorder                = { link = 'XMenuBorder' },
  HoverNormal                = { link = 'XMenu' },
  OutlinePreviewBorder       = { link = 'XMenuBorder' },
  OutlinePreviewNormal       = { link = 'XMenu' },
  RenameBorder               = { link = 'XMenuBorder' },
  RenameNormal               = { link = 'XMenu' },
  TerminalBorder             = { link = 'XMenuBorder' },
  TerminalNormal             = { link = 'XMenu' },
  SagaNormal                 = { link = 'XMenu' },
  SagaBorder                 = { link = 'XMenuBorder' },
  StatusLine                 = { bg = colors.background, fg = colors.foreground },
  -- Mason
  MasonHeader                = { link = 'XMenu' },
  MasonNormal                = { link = 'XMenu' },
  NvimTreeCursorColumn       = { bg = 'none', fg = 'none' },
  NvimTreeCursorLine         = { bg = colors.dark_grey, fg = colors.purple },
  -- Telescope
  TelescopeBorder            = { link = 'XMenuBorder' },
  TelescopePromptBorder      = { link = 'XMenuBorder' },
  TelescopePromptNormal      = { link = 'XMenu', fg = colors.foreground },
  TelescopePromptPrefix      = { link = 'XMenu', fg = colors.foreground },
  TelescopeNormal            = { bg = colors.background },
  TelescopePreviewBorder     = { link = 'XMenuBorder' },
  TelescopePreviewNormal     = { link = 'XMenu', fg = colors.foreground },
  TelescopePreviewTitle      = { fg = colors.background, bg = colors.light_orange },
  TelescopePreviewLine       = { fg = colors.background, bg = colors.orange },
  TelescopePromptTitle       = { fg = colors.background, bg = colors.light_orange },
  TelescopeResultsTitle      = { fg = colors.background, bg = colors.light_orange },
  TelescopeResultsBorder     = { link = 'XMenuBorder' },
  TelescopeResultsNormal     = { link = 'XMenu' },
  -- Transparent background
  FoldCoumn                  = { bg = 'none' },
  NormalNC                   = { bg = 'none', fg = colors.foreground },
  WinSeparator               = { bg = 'none', fg = colors.grey },
  -- Language Syntax
  Boolean                    = { fg = colors.grey },
  Character                  = { fg = colors.yellow },
  Conditional                = { fg = colors.blue },
  Debug                      = { fg = colors.green },
  Define                     = { fg = colors.green },
  Delimiter                  = { fg = colors.grey },
  Exception                  = { fg = colors.dark_orange },
  Float                      = { fg = colors.light_pink },
  Function                   = { fg = colors.foreground },
  Ignore                     = { fg = colors.light_grey },
  Include                    = { fg = colors.dark_orange },
  Keyword                    = { fg = colors.grey },
  Label                      = { fg = colors.grey },
  Macro                      = { fg = colors.dark_orange },
  Number                     = { fg = colors.light_pink },
  PreCondit                  = { fg = colors.dark_orange },
  Repeat                     = { fg = colors.grey },
  SpecialChar                = { fg = colors.dark_orange },
  SpecialComment             = { fg = colors.orange },
  StorageClass               = { fg = colors.light_orange },
  String                     = { fg = colors.foreground },
  Structure                  = { fg = colors.light_orange },
  Tag                        = { fg = colors.orange },
  Typedef                    = { fg = colors.foreground },
  -- Rest
  CursorColumn               = { bg = 'none', fg = colors.purple },
  ErrorMsg                   = { bg = 'none', fg = colors.red },
  NormalFloat                = { bg = colors.dark_grey },
  SpellBad                   = { bg = 'none', fg = 'none', undercurl = true, ctermbg = 'none', ctermfg = 'none' },
  SpellLocal                 = { bg = 'none', fg = 'none', undercurl = true, ctermbg = 'none', ctermfg = 'none' },
  SpellRare                  = { bg = 'none', fg = 'none', undercurl = true, ctermbg = 'none', ctermfg = 'none' },
  -- Diagnostic
  DiagnosticBorder           = { link = 'XMenu' },
  DiagnosticNormal           = { link = 'XMenu' },
  DiagnosticError            = { fg = colors.red },
  DiagnosticFloatingError    = { link = 'NormalFloat' },
  DiagnosticFloatingHint     = { link = 'NormalFloat' },
  DiagnosticFloatingInfo     = { link = 'NormalFloat' },
  DiagnosticFloatingWarn     = { link = 'NormalFloat' },
  DiagnosticSignHint         = { fg = colors.grey, bold = true, bg = 'none' },
  DiagnosticUnderlineError   = { undercurl = true },
  DiagnosticVirtualTextHint  = { bg = 'none' },
  DiagnosticWarn             = { fg = colors.yellow },
  -- nvim cmp
  CmpItemAbbr                = { fg = colors.foreground },
  CmpItemAbbrMatch           = { fg = colors.dark_orange },
  CmpItemAbbrMatchFuzzy      = { fg = colors.dark_orange },
  CmpBorder                  = { link = 'FloatBorder' },
  CmpDocBorder               = { link = 'FloatBorder' },
  CmpItemMenuDefault         = { link = 'NormalFloat' },
  CmpMenu                    = { link = 'NormalFloat' },
  -- cmp item kinds
  CmpItemKindConstant        = { fg = colors.light_pink },
  CmpItemKindFunction        = { fg = colors.blue },
  CmpItemKindIdentifier      = { fg = colors.purple },
  CmpItemKindField           = { fg = colors.dark_orange },
  CmpItemKindVariable        = { fg = colors.purple },
  CmpItemKindSnippet         = { fg = colors.light_pink },
  CmpItemKindText            = { fg = colors.foreground },
  CmpItemKindStructure       = { fg = colors.blue },
  CmpItemKindType            = { fg = colors.orange },
  CmpItemKindKeyword         = { fg = colors.blue },
  CmpItemKindMethod          = { fg = colors.purple },
  CmpItemKindConstructor     = { fg = colors.blue },
  CmpItemKindFolder          = { fg = colors.blue },
  CmpItemKindModule          = { fg = colors.dark_orange },
  CmpItemKindProperty        = { fg = colors.dark_orange },
  CmpItemKindEnum            = { fg = colors.blue },
  CmpItemKindUnit            = { fg = colors.green },
  CmpItemKindClass           = { fg = colors.blue },
  CmpItemKindFile            = { fg = colors.blue },
  CmpItemKindInterface       = { fg = colors.blue },
  CmpItemKindColor           = { fg = colors.yellow },
  CmpItemKindReference       = { fg = colors.blue },
  CmpItemKindEnumMember      = { fg = colors.green },
  CmpItemKindStruct          = { fg = colors.blue },
  -- CmpItemKindValue = { fg = "" },
  -- CmpItemKindEvent = { fg = "" },
  CmpItemKindOperator        = { fg = colors.purple },
  CmpItemKindTypeParameter   = { fg = colors.light_pink },
  CmpItemKindCopilot         = { fg = colors.green },
  -- Diffview
  DiffViewSignColumn         = { bg = 'none' },
  -- Treesitter
  -- ['@string'] = { fg = colors.yellow, bg = '' },
  ['@boolean']               = { fg = colors.grey },
  ['@character']             = { fg = colors.foreground },
  ['@character.special']     = { fg = colors.light_grey },
  ['@comment']               = { link = 'Comment' },
  ['@conditional']           = { fg = colors.grey },
  ['@constant']              = { fg = colors.foreground },
  ['@constant.builtin']      = { fg = colors.grey },
  ['@constant.macro']        = { fg = colors.grey },
  ['@constructor']           = { fg = colors.foreground },
  ['@debug']                 = { link = 'Debug' },
  ['@define']                = { link = "Define" },
  ['@exception']             = { fg = colors.grey },
  ['@field']                 = { link = 'Identifier' },
  ['@field.yaml']            = { fg = colors.light_orange },
  ['@float']                 = { fg = colors.light_pink },
  ['@function']              = { link = 'Function' },
  ['@function.builtin']      = { fg = colors.grey },
  ['@function.macro']        = { fg = colors.grey },
  ['@include']               = { fg = colors.grey },
  ['@keyword']               = { link = 'Keyword' },
  ['@keyword.operator']      = { fg = colors.purple },
  ['@label']                 = { fg = colors.blue },
  ['@macro']                 = { fg = colors.dark_orange },
  ['@method']                = { fg = colors.foreground },
  ['@namespace']             = { fg = colors.foreground },
  ['@number']                = { link = 'Number' },
  ['@operator']              = { link = 'Operator' },
  ['@parameter']             = { fg = colors.foreground },
  ['@preproc']               = { link = 'PreProc' },
  ['@property']              = { fg = colors.grey },
  ['@punctuation.Special']   = { fg = colors.grey },
  ['@punctuation.bracket']   = { fg = colors.grey },
  ['@punctuation.delimiter'] = { fg = colors.grey },
  ['@repeat']                = { link = 'Repeat' },
  ['@storageclass']          = { link = 'StorageClass' },
  ['@string.escape']         = { fg = colors.dark_orange },
  ['@string.regex']          = { fg = colors.dark_orange },
  ['@string.special']        = { fg = colors.dark_orange },
  ['@structure']             = { link = 'Structure' },
  ['@tag']                   = { link = 'Tag' },
  ['@tag.attribute']         = { fg = colors.foreground },
  ['@tag.delimiter']         = { fg = colors.purple },
  ['@text.danger']           = { fg = colors.dark_orange },
  ['@text.literal']          = { link = 'String' },
  ['@text.reference']        = { fg = colors.grey },
  ['@text.strong']           = { bold = true },
  ['@text.title']            = { link = 'Title' },
  ['@text.todo']             = { link = 'Todo' },
  ['@text.underline']        = { link = 'Underlined' },
  ['@text.uri']              = { fg = colors.blue },
  ['@text.warning']          = { link = 'Todo' },
  ['@type']                  = { link = 'Type' },
  ['@type.definition']       = { link = 'Typedef' },
  ['@variable']              = { fg = colors.foreground },
  ['@variable.builtin']      = { fg = colors.foreground },
}

local M = {}

function M.load()
  vim.cmd [[hi clear]]
  for group, hl in pairs(theme) do
    vim.api.nvim_set_hl(0, group, hl)
  end
end

return M
